name: Hola mundo // Nombre del flujo de trabajo

on: [push] // Dispara el flujo de trabajo en cada push

jobs:
  hola: // Define un trabajo llamado "hola"
    runs-on: ubuntu-latest // Usa la última versión de Ubuntu

    steps:
    - name: Hola Mundo // Nombre del paso
      run: echo "Hola Mundo" // Comando para imprimir "Hola Mundo" en la consola